---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: update-api-sa
  namespace: default
  labels:
    app: update-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: update-api-cr
  labels:
    app: update-api
rules:
  - apiGroups:
      - 'apps'
    resources:
      - deployments
      - namespaces
    verbs:
      - get
      - list
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: update-api-rb
roleRef:
  kind: ClusterRole
  name: update-api-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: update-api-sa
    namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: update-api-sa-secret
  annotations:
    kubernetes.io/service-account.name: update-api-sa
type: kubernetes.io/service-account-token
---