apiVersion: v1
kind: Service
metadata:
  name: update-api-svc
  labels:
    app: update-api
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: api
    protocol: TCP
  selector:
    app: update-api
