name: build binary and container image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        cd cmd/kube-api
        go build

    - name: Build Image
      run: |
        docker build -t docker.richardjameskendall.com/kube-update-api .
    
    - name: Login to private registry
      run: echo ${{secrets.REGO_PW}} | docker login docker.richardjameskendall.com -u ${{secrets.REGO_USER}} --password-stdin
    
    - name: Push to registry
      run: docker push docker.richardjameskendall.com/kube-update-api
